import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticketing App",
  description: "Generated by Allsamir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="https://cdn.iconscout.com/icon/free/png-256/free-ticket-1855957-1574163.png?f=webp&w=256"
          type="image"
        />
      </head>
      <body className={inter.className}>
        <Navbar />
        <div className="bg-page">{children}</div>
      </body>
    </html>
  );
}
